### PR TITLE
added all the blogposts

### PR DESCRIPTION
**Pull request by mimoo**

### CODE REVIEW

**Comment by tomrittervg** [comment]
I think definition.png is missing

**Comment by tomrittervg** [comment]
Also in #2, in your binomial mathjax, for me when I preview it it shows a red "\mathchoice"... Do you see that?

(If you aren't previewing it, you should install ruby and jekyll and then type 'jekyll serve' in the directory.)

**Comment by mimoo** [comment]
I am using 'jekyll serve' but didn't see that "\mathchoice" mmm..

**Comment by mimoo** [comment]
OK everything's fine now :) instead of hosting all the mathjax files I am just hosting the necessary files (" I check the missing files in the network tab of firefox"). Might not be a great solution since things might break in the future...

**Comment by mimoo** [comment]
:+1:

**Pull request merged**
